services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.new
    ports:
      - "8089:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=golf_club
      - DB_USER=root
      - DB_PASSWORD=password
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=golf_club
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: